<?php

namespace Database\Seeders;

use App\Models\Supply;
use Illuminate\Database\Seeder;

class SupplySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $supplies = [
            [
                'code' => 'ATK001',
                'name' => 'Ballpoint Pen',
                'category' => 'ATK',
                'unit' => 'pcs',
                'current_stock' => 100,
                'min_stock' => 20,
                'price' => 2500,
                'description' => 'Blue ballpoint pen',
            ],
            [
                'code' => 'ATK002',
                'name' => 'A4 Paper',
                'category' => 'ATK',
                'unit' => 'ream',
                'current_stock' => 50,
                'min_stock' => 10,
                'price' => 45000,
                'description' => 'A4 paper 70gsm',
            ],
            [
                'code' => 'CLEAN001',
                'name' => 'Detergent',
                'category' => 'Cleaning',
                'unit' => 'bottle',
                'current_stock' => 15,
                'min_stock' => 5,
                'price' => 25000,
                'description' => 'Floor cleaner detergent',
            ],
            [
                'code' => 'PANTRY001',
                'name' => 'Coffee',
                'category' => 'Pantry',
                'unit' => 'kg',
                'current_stock' => 8,
                'min_stock' => 3,
                'price' => 75000,
                'description' => 'Coffee beans for office',
            ],
            [
                'code' => 'GAC001',
                'name' => 'Gulaku',
                'category' => 'Food & Beverages',
                'unit' => 'kg',
                'current_stock' => 0,
                'min_stock' => 5,
                'price' => 0,
                'description' => 'Gulaku@1kg',
            ],
            [
                'code' => 'GAC002',
                'name' => 'Kapal Api',
                'category' => 'Food & Beverages',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Kapal Api@380g',
            ],
            [
                'code' => 'GAC003',
                'name' => 'Sariwangi',
                'category' => 'Food & Beverages',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Sariwangi@190g',
            ],
            [
                'code' => 'GAC004',
                'name' => 'ABC',
                'category' => 'Food & Beverages',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'ABC@600ml',
            ],
            [
                'code' => 'GAC005',
                'name' => 'ABC',
                'category' => 'Food & Beverages',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'ABC@600ml',
            ],
            [
                'code' => 'GAC006',
                'name' => 'Maxcreamer',
                'category' => 'Food & Beverages',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Maxcreamer@500g',
            ],
            [
                'code' => 'GAC007',
                'name' => 'Nice',
                'category' => 'Food & Beverages',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Nice@1000g',
            ],
            [
                'code' => 'GAC008',
                'name' => 'Nice',
                'category' => 'Food & Beverages',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Nice@1000g',
            ],
            [
                'code' => 'GAC009',
                'name' => 'Sunlight',
                'category' => 'Household Cleaning',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Sunlight@800ml',
            ],
            [
                'code' => 'GAC010',
                'name' => 'Lifeboy',
                'category' => 'Personal Care',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Lifeboy@450ml',
            ],
            [
                'code' => 'GAC011',
                'name' => 'Rejoice',
                'category' => 'Personal Care',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Rejoice@320ml',
            ],
            [
                'code' => 'GAC012',
                'name' => 'Pepsodent',
                'category' => 'Personal Care',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Pepsodent@160g',
            ],
            [
                'code' => 'GAC013',
                'name' => 'Soklin',
                'category' => 'Household Cleaning',
                'unit' => 'Kg',
                'current_stock' => 0,
                'min_stock' => 5,
                'price' => 0,
                'description' => 'Soklin@1Kg',
            ],
            [
                'code' => 'GAC014',
                'name' => 'Vape',
                'category' => 'Home & Pest Control',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Vape@600g',
            ],
            [
                'code' => 'GAC015',
                'name' => 'Sos',
                'category' => 'Food & Beverages',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Sos@860ml',
            ],
            [
                'code' => 'GAC016',
                'name' => 'Clink',
                'category' => 'Household Cleaning',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Clink@425ml',
            ],
            [
                'code' => 'GAC017',
                'name' => 'Vixal',
                'category' => 'Household Cleaning',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Vixal@800ml',
            ],
            [
                'code' => 'GAC018',
                'name' => 'Stella',
                'category' => 'Home & Pest Control',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Stella@400ml',
            ],
            [
                'code' => 'GAC019',
                'name' => 'Swallow',
                'category' => 'Food & Beverages',
                'unit' => 'pcs',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Swallow@isi4',
            ],
            [
                'code' => 'GAC020',
                'name' => 'Pladge',
                'category' => 'Household Cleaning',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Pladge@450ml',
            ],
            [
                'code' => 'GAC021',
                'name' => 'Yuri',
                'category' => 'Household Cleaning',
                'unit' => 'ml',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'Yuri@1000ml',
            ],
            [
                'code' => 'GAC022',
                'name' => 'Nescaffe Coffee',
                'category' => 'Food & Beverages',
                'unit' => 'g',
                'current_stock' => 0,
                'min_stock' => 10,
                'price' => 0,
                'description' => 'nescaffe coffe@100gram',
            ],
            // GAA Series - Office Supplies & Stationery (146 items)
            ['code' => 'GAA001', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko @1box kecil = 12 pcs'],
            ['code' => 'GAA002', 'name' => 'Pop 1', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Pop 1 @1box = 12 pcs'],
            ['code' => 'GAA003', 'name' => 'Joyko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @1box kecil = 12 pcs'],
            ['code' => 'GAA004', 'name' => 'Data Print', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Data Print @1 Pack = 50 Sheet'],
            ['code' => 'GAA005', 'name' => 'Garda', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Garda @1 Pack = 100 pcs'],
            ['code' => 'GAA006', 'name' => 'Biola', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Biola @1 Pack = 50 pcs'],
            ['code' => 'GAA007', 'name' => 'Eka Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Eka Tape @24mm'],
            ['code' => 'GAA008', 'name' => 'Eka Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Eka Tape @48mm'],
            ['code' => 'GAA009', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @48mm'],
            ['code' => 'GAA010', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @48mm'],
            ['code' => 'GAA011', 'name' => 'Asahi', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Asahi @1 Pack = 100 Sheet'],
            ['code' => 'GAA012', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA013', 'name' => 'Daito', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daito @1 Pack = 100 Sheet'],
            ['code' => 'GAA014', 'name' => 'E-Print', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'E-Print @1 Pack = 100 Sheet'],
            ['code' => 'GAA015', 'name' => 'Paperline', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Paperline @90'],
            ['code' => 'GAA016', 'name' => 'Paper Item', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@90'],
            ['code' => 'GAA017', 'name' => 'Erica', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Erica @156'],
            ['code' => 'GAA018', 'name' => 'Kangaro', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kangaro @1box kecil = 20 ea'],
            ['code' => 'GAA019', 'name' => 'Joyko HL-2', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @HL-2'],
            ['code' => 'GAA020', 'name' => 'Joyko HL-2', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @HL-2'],
            ['code' => 'GAA021', 'name' => 'Joyko SC-848', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @SC-848'],
            ['code' => 'GAA022', 'name' => 'Pencil Lead 2B', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@2B'],
            ['code' => 'GAA023', 'name' => 'Paperline A5', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Paperline @A5'],
            ['code' => 'GAA024', 'name' => 'Snowman', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman @500'],
            ['code' => 'GAA025', 'name' => 'Sellery', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Sellery @100 meters'],
            ['code' => 'GAA026', 'name' => 'Joyko No. 85', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @No. 85'],
            ['code' => 'GAA027', 'name' => 'Kangaro', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kangaro @1box kecil = 20 ea'],
            ['code' => 'GAA028', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @12mm'],
            ['code' => 'GAA029', 'name' => 'Snowman WP-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman WP-12'],
            ['code' => 'GAA030', 'name' => 'Snowman BG-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman BG-12'],
            ['code' => 'GAA031', 'name' => 'Snowman BG-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman BG-12'],
            ['code' => 'GAA032', 'name' => 'Snowman BG-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman BG-12'],
            ['code' => 'GAA033', 'name' => 'Snowman BG-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman BG-12'],
            ['code' => 'GAA034', 'name' => 'Joyko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @1box kecil = 50 pcs'],
            ['code' => 'GAA035', 'name' => 'Citizen CT812-BN', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Citizen @CT812-BN'],
            ['code' => 'GAA036', 'name' => 'Snowman V-7', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman @V-7'],
            ['code' => 'GAA037', 'name' => 'Paperline', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Paperline @108x155 mm'],
            ['code' => 'GAA038', 'name' => 'Paperline', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Paperline @40 Sheets'],
            ['code' => 'GAA039', 'name' => 'ABC Alkaline', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'ABC Alkaline'],
            ['code' => 'GAA040', 'name' => 'Panasonic', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'Panasonic'],
            ['code' => 'GAA041', 'name' => 'Panasonic', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'Panasonic'],
            ['code' => 'GAA042', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA043', 'name' => 'Paper A4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@A4'],
            ['code' => 'GAA044', 'name' => 'Artline EPG-4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Artline EPG-4'],
            ['code' => 'GAA045', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA046', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA047', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA048', 'name' => 'Paper F4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@F4'],
            ['code' => 'GAA049', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @24mm'],
            ['code' => 'GAA050', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @12mm'],
            ['code' => 'GAA051', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @48mm'],
            ['code' => 'GAA052', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @12mm'],
            ['code' => 'GAA053', 'name' => 'Kiky', 'category' => 'ATK', 'unit' => 'rim', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kiky @1 Rim'],
            ['code' => 'GAA054', 'name' => 'Bola Dunia', 'category' => 'ATK', 'unit' => 'rim', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Bola Dunia @1 Rim'],
            ['code' => 'GAA055', 'name' => 'SIDU', 'category' => 'ATK', 'unit' => 'rim', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'SIDU @1 Rim'],
            ['code' => 'GAA056', 'name' => 'e-Print', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'e-Print @1 Pack = 20 Sheet'],
            ['code' => 'GAA057', 'name' => 'Kenko L-150', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko L-150 @1 Pack'],
            ['code' => 'GAA058', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko @1box'],
            ['code' => 'GAA059', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko'],
            ['code' => 'GAA060', 'name' => 'Epson T6641', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson T6641'],
            ['code' => 'GAA061', 'name' => 'Epson T6644', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson T6644'],
            ['code' => 'GAA062', 'name' => 'Epson T6642', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson T6642'],
            ['code' => 'GAA063', 'name' => 'Epson T6643', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson T6643'],
            ['code' => 'GAA064', 'name' => '3M VHB', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '3M VHB @12mm'],
            ['code' => 'GAA065', 'name' => '3M VHB', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '3M VHB @24mm'],
            ['code' => 'GAA066', 'name' => 'Snowman BG-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman BG-12'],
            ['code' => 'GAA067', 'name' => 'Snowman G-12', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman G-12'],
            ['code' => 'GAA068', 'name' => 'Joyko', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko'],
            ['code' => 'GAA069', 'name' => 'Paperline', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Paperline @40 Sheets'],
            ['code' => 'GAA070', 'name' => 'Ruler 30cm', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@30 cm'],
            ['code' => 'GAA071', 'name' => 'BIG Sticker', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'BIG 51x38 mm'],
            ['code' => 'GAA072', 'name' => 'BIG Sticker', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'BIG 76x76 mm'],
            ['code' => 'GAA073', 'name' => 'Spon', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Spon'],
            ['code' => 'GAA074', 'name' => 'Joyko', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @50cc'],
            ['code' => 'GAA075', 'name' => 'Jaya', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Jaya @1Pack = 100 Ea'],
            ['code' => 'GAA076', 'name' => 'FB', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'FB'],
            ['code' => 'GAA077', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @48mm'],
            ['code' => 'GAA078', 'name' => 'Ruler 20cm', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@20cm'],
            ['code' => 'GAA079', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko @50pcs'],
            ['code' => 'GAA080', 'name' => 'ABC Alkaline', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'ABC Alkaline'],
            ['code' => 'GAA081', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA082', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA083', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA084', 'name' => 'Joyko SC-848', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko @SC-848'],
            ['code' => 'GAA085', 'name' => 'Kenko L500', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko L500'],
            ['code' => 'GAA086', 'name' => 'UHU Besar', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'UHU Besar'],
            ['code' => 'GAA087', 'name' => 'Data Print', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Data Print @1 Pack = 20 Sheet'],
            ['code' => 'GAA088', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko'],
            ['code' => 'GAA089', 'name' => 'Snowman', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman'],
            ['code' => 'GAA090', 'name' => 'ABC Alkaline', 'category' => 'IT/Electronics', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'ABC Alkaline (1 Kotak = 12 ea)'],
            ['code' => 'GAA091', 'name' => 'Eka Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Eka Tape @12mm'],
            ['code' => 'GAA092', 'name' => 'Castol', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Castol'],
            ['code' => 'GAA093', 'name' => 'Paper', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@28x40'],
            ['code' => 'GAA094', 'name' => 'Paper A3', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@A3'],
            ['code' => 'GAA095', 'name' => 'Snowman', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Snowman'],
            ['code' => 'GAA096', 'name' => 'Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@48mm'],
            ['code' => 'GAA097', 'name' => 'Alteco', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Alteco'],
            ['code' => 'GAA098', 'name' => 'Paperline', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Paperline @108x155 mm'],
            ['code' => 'GAA099', 'name' => 'Paper F4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'F4'],
            ['code' => 'GAA100', 'name' => 'Paper 1/2 A4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1/2 A4'],
            ['code' => 'GAA101', 'name' => 'UHU Kecil', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'UHU Kecil'],
            ['code' => 'GAA102', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @24mm'],
            ['code' => 'GAA103', 'name' => 'Eraser', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Eraser'],
            ['code' => 'GAA104', 'name' => 'Paper Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 100 Sheet'],
            ['code' => 'GAA105', 'name' => 'Bola Dunia', 'category' => 'ATK', 'unit' => 'rim', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Bola Dunia @1 Rim'],
            ['code' => 'GAA106', 'name' => 'Printer HP 85A', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Printer HP 85A'],
            ['code' => 'GAA107', 'name' => 'Printer HP 78A', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Printer HP 78A'],
            ['code' => 'GAA108', 'name' => 'BIG Sticker', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'BIG 76x51 mm'],
            ['code' => 'GAA109', 'name' => 'Joyko', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko'],
            ['code' => 'GAA110', 'name' => 'Item', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1pack'],
            ['code' => 'GAA111', 'name' => 'BIG Sticker', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'BIG 44x12 mm'],
            ['code' => 'GAA112', 'name' => 'Joyko HD-10', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Joyko HD-10'],
            ['code' => 'GAA113', 'name' => 'Epson 0031', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson 0031'],
            ['code' => 'GAA114', 'name' => 'Epson 0032', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson 0032'],
            ['code' => 'GAA115', 'name' => 'Epson 0033', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson 0033'],
            ['code' => 'GAA116', 'name' => 'Epson 0034', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 3, 'price' => 0, 'description' => 'Epson 0034'],
            ['code' => 'GAA117', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko @1box'],
            ['code' => 'GAA118', 'name' => 'Data Print', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Data Print @1 Pack = 20 Sheet'],
            ['code' => 'GAA119', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko @1box=12ea'],
            ['code' => 'GAA120', 'name' => 'Daimaru', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Daimaru @24mm'],
            ['code' => 'GAA121', 'name' => 'Gold Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Gold Tape @12mm'],
            ['code' => 'GAA122', 'name' => 'Sticker', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => '20x50 mm'],
            ['code' => 'GAA123', 'name' => 'Epoxy', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Epoxy'],
            ['code' => 'GAA124', 'name' => '3M', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '3M'],
            ['code' => 'GAA125', 'name' => 'Fargo', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Fargo'],
            ['code' => 'GAA126', 'name' => 'Paper', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '90x120cm'],
            ['code' => 'GAA127', 'name' => 'Kenko Deluxe', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko Deluxe'],
            ['code' => 'GAA128', 'name' => 'Penghapus', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Penghapus'],
            ['code' => 'GAA129', 'name' => 'Kenko', 'category' => 'ATK', 'unit' => 'box', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Kenko @1box'],
            ['code' => 'GAA130', 'name' => 'Paper A4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@A4'],
            ['code' => 'GAA131', 'name' => 'Paper A4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@A4'],
            ['code' => 'GAA132', 'name' => 'e-Print', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'e-Print @1 Pack = 20 Sheet'],
            ['code' => 'GAA133', 'name' => 'Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@12mm'],
            ['code' => 'GAA134', 'name' => 'Panasonic', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'Panasonic'],
            ['code' => 'GAA135', 'name' => 'Panasonic', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 10, 'price' => 0, 'description' => 'Panasonic'],
            ['code' => 'GAA136', 'name' => 'Dextone', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Dextone'],
            ['code' => 'GAA137', 'name' => 'Electrical Tape', 'category' => 'ATK', 'unit' => 'roll', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Electrical Tape'],
            ['code' => 'GAA138', 'name' => 'Paper', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '76x110mm'],
            ['code' => 'GAA139', 'name' => 'e-print', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'e-print'],
            ['code' => 'GAA140', 'name' => 'Papanscanner', 'category' => 'IT/Electronics', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 2, 'price' => 0, 'description' => 'Papanscanner'],
            ['code' => 'GAA141', 'name' => 'Item Pack', 'category' => 'ATK', 'unit' => 'pack', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Pack = 12 Pcs'],
            ['code' => 'GAA142', 'name' => 'Paper A4', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@A4'],
            ['code' => 'GAA143', 'name' => 'Papertray', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Papertray'],
            ['code' => 'GAA144', 'name' => 'Deskpenholder', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Deskpenholder'],
            ['code' => 'GAA145', 'name' => 'Paper', 'category' => 'ATK', 'unit' => 'rim', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => '@1 Rim'],
            ['code' => 'GAA146', 'name' => 'Bantex Box File', 'category' => 'ATK', 'unit' => 'pcs', 'current_stock' => 0, 'min_stock' => 5, 'price' => 0, 'description' => 'Bantex Box File'],
        ];

        foreach ($supplies as $supply) {
            Supply::updateOrCreate(
                ['code' => $supply['code']],
                $supply
            );
        }
    }
}
